### ISSUE TITLE
。。。加入网易云音乐的账密后报错

### ISSUE THREAD

**Issue by zhuyaozi** [Sitoi/dailycheckin#11]
## 1.关于你要提交的问题

Q：是否搜索了 issue（包括已关闭的issue）

- [X] 没有类似的 issue 

Q：是否仔细阅读了教程

- [X] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装 Python
- [X] 方法二：Docker
- [ ] 方法三：腾讯云函数
- [ ] 方法四：GitHub Actions

### (1) 具体问题

A：。。。加入网易云音乐的账密后报错，确认过了账号密码没问题
      。。。请教一下，是不是哪里我没搞对

### (2) 详细日志

A：/dailycheckin # python3 ./music163/music163.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='music.163.com', port=443): Max retries exceeded with url: /weapi/login/cellphone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./music163/music163.py", line 149, in <module>
    Music163CheckIn(music163_account_list=_music163_account_list).main()
  File "./music163/music163.py", line 138, in main
    sign_msg, music_count_msg = self.sign(session=session, phone=phone, password=password)
  File "./music163/music163.py", line 68, in sign
    res = session.post(url=url, data=self.protect(json.dumps(logindata)), headers=headers2)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='music.163.com', port=443): Max retries exceeded with url: /weapi/login/cellphone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))

**Comment by Sitoi** [comment]
我更想了 ，你重启 docker 试试吧 可能可以修复 你这是 ssl 问题

**Comment by zhuyaozi** [comment]
> 我更新了 ，你重启 docker 试试吧 可能可以修复 你这是 ssl 问题

感谢，已经可以了！
