### ISSUE TITLE
在Docker中执行时，出现这情况，如何修复？？

### ISSUE THREAD

**Issue by VPN-V2Ray** [Sitoi/dailycheckin#26]
使用配置文件路径: /dailycheckin/config/config.json
Traceback (most recent call last):
  File "/usr/local/bin/dailycheckin", line 8, in <module>
    sys.exit(checkin())
  File "/usr/local/lib/python3.8/site-packages/dailycheckin/main.py", line 25, in checkin
    data = json.loads(f.read())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 30 column 228 (char 871)

**Comment by lexno** [comment]
配置文件出问题了，看看config.json第30行
