### ISSUE TITLE
[Bug] 第一天还是可以签到的，第二就不行了

### ISSUE THREAD

**Issue by optlsz** [Sitoi/dailycheckin#464]
### 💻 系统环境

Other Linux

### 📦 部署环境

Docker

### 🐛 问题描述

已经成功运行过了，隔了一天就提示这个

## 开始执行... 2024-12-04 10:03:42

Traceback (most recent call last):
  File "/usr/local/bin/dailycheckin", line 5, in <module>
    from dailycheckin.main import checkin
  File "/usr/local/lib/python3.11/site-packages/dailycheckin/__init__.py", line 11, in <module>
    __import__(_modname)
  File "/usr/local/lib/python3.11/site-packages/dailycheckin/acfun/main.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by NightGlowww** [comment]
你这不是没有安装requests模块吗？
